name: React App CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (optional: replace with your test script)
      - name: Run tests
        run: npm test -- --coverage

  docker-build:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the build job finishes before this job runs

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build Docker image
      - name: Build Docker image
        run: |
          docker buildx build -t my-react:v1 -f Dockerfile .

      # List Docker images to verify the image exists
      - name: List Docker images
        run: docker images

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Tag Docker image with Docker Hub repo name
      - name: Tag Docker image
        run: docker tag my-react:v1 zainmk280/my-react:v1

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker-Hub
        run: docker push zainmk280/my-react:v1
