name: React App CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (optional: replace with your test script)
      - name: Run tests
        run: npm test -- --coverage

  docker-build:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the build job finishes before this job runs

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t zainmk280/react-app .

      # Optionally, push the image to Docker Hub (replace with your DockerHub credentials)
      - name: Push Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag zainmk280/react-app:latest zainmk280/react-app:v1
          docker push zainmk280/react-app:v1

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build  # Ensure docker build is successful before deploying

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy steps (for example, deploying to a cloud service or server)
      - name: Deploy to production (Placeholder)
        run: |
          echo "Deploying the app to production (this is a placeholder step)"
          # Add your deployment script here, such as SSH deployment or API calls
